version: "3.8"

# Production overrides
services:
  backend:
    environment:
      - ENVIRONMENT=production
      - DEBUG=false
    restart: always
    command: gunicorn app.main:app -w 4 -k uvicorn.workers.UvicornWorker -b 0.0.0.0:8000

  celery-worker:
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    restart: always

  nginx:
    restart: always

  redis:
    restart: always

  postgres:
    restart: always
